scan_merger: ros__parameters: destination_frame: base_link scan_destination_topic: /scan_merged laserscan_topics: - /scan_front - /scan_rear
angle_min: -3.14
angle_max: 3.14
angle_increment: 0.0058
use_pointcloud: False
publish_frequency: 10.0

