slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    scan_topic: /scan_360

    # Một số tham số cơ bản
    resolution: 0.05
    max_laser_range: 10.0
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    transform_publish_period: 0.05
    
    mode: mapping  # chỉ mapping online



